ICU-21282 Fixup date patterns and date field symbols display
unicode-org/icu pull request #1327
Opened 2020-09-12 22:53 UTC by 7h3w1zz

No content changes.  This make the display of date patterns, date field symbols, and skeletons consistent.
- Date field symbols are in a code block (e.g. `y` or `yyyy`)
- Date patterns are quoted in a code block (e.g. `"y"` or `"MMMM d 'at' h:mm a"`)
- Skeletons are the same as date patterns (e.g. "`MMMMdjmm`")
- Strings that might be the result of a date pattern are quoted (e.g. "April 2 at 5:00 PM")
Thus `"y"` denotes the date pattern containing the date field symbol `y`

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21282
- [x] Updated PR title and link in previous line to include Issue number
- [ ] Issue accepted
- [x] Tests included
- [x] Documentation is changed or added

2020-09-12 22:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/unicode-org/icu?pullRequest=1327) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/unicode-org/icu?pullRequest=1327) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unicode-org/icu?pullRequest=1327) it.</sub>

2020-09-23 17:46 UTC, pedberg-icu approved these changes

2020-09-23 17:50 UTC, pedberg-icu requested changes
The changes look good, thanks, but commit message must begin with the Jira ticket number, i.e.
`ICU-21282 Fixup date patterns and date field symbols display`
Please update the commit message, thanks.

2020-09-23 19:41 UTC, 7h3w1zz commented
Rebased on master and changed commit message.

2020-09-23 20:43 UTC, 7h3w1zz commented
Missed a typo in the commit message, should be good now :roll_eyes:

2020-09-23 22:49 UTC, pedberg-icu approved these changes
Thanks, looks good!

2020-09-23 22:49 UTC, merged