ICU-21410 fix int32_t overflow in listFormat
unicode-org/icu pull request #1479
Opened 2020-11-20 00:20 UTC by FrankYFTang

##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21410
- [X] Updated PR title and link in previous line to include Issue number
- [ ] Issue accepted
- [X] Tests included
- [X] Documentation is changed or added

2020-11-20 00:28 UTC, sffc requested changes

2020-11-20 00:28 UTC, sffc commented on icu4c/source/i18n/formatted_string_builder.cpp
> +    U_ASSERT(position >= 0);
Can you put all these `U_ASSERT`s inside prepareForInsert?

2020-11-20 00:28 UTC, sffc commented on icu4c/source/i18n/formatted_string_builder.cpp
> +        if ((fLength + count) > std::numeric_limits<int32_t>::max() / 2) {
You can use `INT32_MAX` instead in ICU4C

2020-11-20 00:44 UTC, FrankYFTang commented
PTAL

2020-11-23 19:18 UTC, sffc approved these changes

2020-11-23 19:18 UTC, sffc commented
LGTM please squash

2020-11-23 19:39 UTC, FrankYFTang commented
squashed , please approve again

2020-11-23 19:49 UTC, sffc approved these changes

2020-11-24 01:12 UTC, merged