ICU-21349 adding tests to prove the .usage("") unset the existing usage
unicode-org/icu pull request #1614
Opened 2021-03-03 17:53 UTC by younies

##### Checklist

- [ ] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21349
- [ ] Required: The PR title must be prefixed with a JIRA Issue number. 
- [ ] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [ ] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [ ] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

2021-03-04 18:18 UTC, younies commented on icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
> +                new ULocale("en-US"), //
delete `//`

2021-03-04 18:18 UTC, younies commented on icu4j/main/tests/core/src/com/ibm/icu/dev/test/number/NumberFormatterApiTest.java
> +                3048,            //
delete `//`

2021-03-04 23:15 UTC, sffc reviewed
LGTM except for the small formatting fixes you noted.  Thanks!

2021-03-04 23:36 UTC, hugovdm approved these changes
Thanks for fixing!

2021-03-04 23:37 UTC, hugovdm reviewed
(I'll be around to approve again in the morning - agreed with the comment cleanup.)

2021-03-04 23:38 UTC, hugovdm requested changes
(Looks like to unset an "approve", I must explicitly "request changes".)

2021-03-05 20:36 UTC, hugovdm approved these changes
Consider marking PRs "ready for review" rather than leaving them as draft.

The new commit looks good:
https://github.com/unicode-org/icu/commit/65005ec3e3e0dc027e6fa546ff35484762b6b99a

(Is there any way to tell that the commit we reviewed before was https://github.com/unicode-org/icu/commit/39b915f462875fac01f3fd634d26f957d8225462 ?)

2021-03-05 23:37 UTC, merged