layoutengine: update harfbuzz link; + icu-le-hb link
unicode-org/icu pull request #1661
Opened 2021-03-19 06:43 UTC by Artoria2e5

The fd.o harfbuzz link currently goes to the github repo, which is a bit less documentation-ish than the github.io page.

Add link to icu-le-hb.

Wait, JIRA?

##### Checklist

- [ ] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-_____
- [ ] Required: The PR title must be prefixed with a JIRA Issue number. 
- [ ] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [ ] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [ ] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

2021-03-19 06:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/unicode-org/icu?pullRequest=1661) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/unicode-org/icu?pullRequest=1661) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unicode-org/icu?pullRequest=1661) it.</sub>

2021-04-07 17:34 UTC, echeran commented
(sorry for the delay) Yes, you can use this Jira link: https://unicode-org.atlassian.net/browse/ICU-21577.

Would you be able to do the following?

* update the commit message to be prefixed with "ICU-21577 ..."
* update this PR title similarly
* update the PR description & check off the appropriate checkboxes there (should be most of them)

That's all that's needed, the change looks good, thanks!

2021-04-09 14:27 UTC, Artoria2e5 commented
Sorry for the loong delay on the commit amend. Takes quite some time to figure out my proxy for GitHub so I can clone the whole repo. (GH doesn't accept pushes from a shallow clone AFAIK.)

2021-04-20 20:42 UTC, echeran approved these changes
LGTM, Thanks! Merge whenever you're ready.

2021-04-20 20:46 UTC, echeran requested changes
Sorry, actually, a minor commit ammend is required -- I think you need to get rid of the colon in the commit message right after the Jira ticket number

2021-04-23 04:33 UTC, echeran approved these changes
All the checks finally passed now. Merge when ready, thanks!

2021-04-23 06:05 UTC, NsaFunNj commented
lick my balls

Sent from my iPhone

On Apr 23, 2021, at 12:34 AM, Elango ***@***.***> wrote:

﻿
@echeran approved this pull request.

All the checks finally passed now. Merge when ready, thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-05-05 18:09 UTC, merged