period typo
unicode-org/icu pull request #1724
Opened 2021-05-16 02:25 UTC by ddisqq

##### Checklist

- [ ] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-_____
- [ ] Required: The PR title must be prefixed with a JIRA Issue number. 
- [ ] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [ ] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [ ] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

2021-05-16 02:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/unicode-org/icu?pullRequest=1724) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/unicode-org/icu?pullRequest=1724) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unicode-org/icu?pullRequest=1724) it.</sub>

2021-05-16 02:40 UTC, ddisqq commented
How can I file a JIRA?

2021-05-19 17:09 UTC, sven-oly approved these changes

2021-05-19 18:32 UTC, jefgen requested changes
Thanks for creating this PR!

Note that the commit message must contain/start with the JIRA ticket number.
For example: `ICU-21618 Fix typo in icu4c/source/data/translit/en.txt`

You can use `git commit --amend` to change the message:
https://www.atlassian.com/git/tutorials/rewriting-history

2021-05-26 17:52 UTC, closed without merging

2021-05-26 17:53 UTC, pedberg-icu commented
Need to make the change in CLDR, will do as part of other changes