ICU-21656 fix wrong matching categories.
unicode-org/icu pull request #1839
Opened 2021-08-31 14:25 UTC by younies

##### Checklist

- [ ] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21656
- [ ] Required: The PR title must be prefixed with a JIRA Issue number. 
- [ ] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [ ] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [ ] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

2021-08-31 14:30 UTC, younies commented
@sffc , I have used the convertibility instead of simplifying because of the following reasons:

1. If the unit is reciprocal (such as in consumption) it should match
2. it is very hard to simplify: square-meter-per-millimeter.

2021-09-02 02:21 UTC, sffc commented
As discussed in our weekly meeting:

(1) This approach works, but it is fragile to locale data changes and could be slow

(2) The units we are simplifying have no power prefixes

(3) Mark suggested the following algorithm instead:

1. Check if the base unit has an exact match
2. Check if the reciprocal of the base unit has an exact match
3. Check if the fully simplified base unit has an exact match
4. Check if the reciprocal of the fully simplified base unit has an exact match
5. If still no matches, return an error code.

2021-09-02 13:37 UTC, younies commented
@sffc , I have used the new methodology that we have discussed in the meeting and I have added two new tests for unit consumption.

If the code is good for you, I will start porting it to C++.

2021-09-03 14:52 UTC, younies commented
@sffc , now everything is there, ready for final review

2021-09-07 20:00 UTC, sffc reviewed
Almost there!

2021-09-07 23:06 UTC, younies commented on icu4c/source/i18n/measunit_extra.cpp
> +    return result;
First of all, we normalize the units with their SI prefix, so
 - square-kilogram-per-kilogram --> kilogram
 - square-kilogram-per-gram --> square-kilogram-per-gram


Secondly, when we build the `MeasureUnitImpl` to get the Id, we sort the units.

2021-09-07 23:22 UTC, sffc reviewed
LGTM but please fix the build failure reported by CI:

```
   g++	 ...  ../../../icu4c/source/test/intltest/numbertest_decimalquantity.cpp
../../../icu4c/source/test/intltest/numbertest_api.cpp: In member function ‘void NumberFormatterApiTest::unitUsage()’:
../../../icu4c/source/test/intltest/numbertest_api.cpp:1798:47: error: expected ‘)’ before ‘unit’
 1798 |                        NumberFormatter::with()                                     //
      |                                               ^
      |                                               )
 1799 |                        unit(MeasureUnit::forIdentifier("gallon-per-mile", status)) //
      |                        ~~~~                    
../../../icu4c/source/test/intltest/numbertest_api.cpp:1795:23: note: to match this ‘(’
 1795 |     assertFormatSingle(u"gallon-per-mile match the correct category",              //
      |                       ^
```

2021-09-08 21:29 UTC, sffc requested changes
1. Please don't force-push until the end, because it makes it harder to track changes between reviews.
2. The ASAN/Valgrind build is failing; please fix.

2021-09-09 14:30 UTC, younies commented
@sffc , now `asan` is solved, the problem was that when we build the `MeasureUnitImpl`, we need the following:

1. make a copy of `MeasureUnitImpl`, so, it can be used later.
2. we need to keep the `MeasureUnit` after we extract the `identifier` or copy the `identifier`


Here is a problem, to keep the identifier, you need to keep the `MeasureUnit`. I am not sure if returning `const char *` for `getIdentifier()` is a good choice.

2021-09-16 18:01 UTC, younies commented on icu4c/source/i18n/measunit_extra.cpp
> +MeasureUnitImpl MeasureUnitImpl::simplify(UErrorCode &status) const {
done!

2021-09-16 18:54 UTC, younies commented on icu4c/source/i18n/measunit_extra.cpp
> +    StringPiece identifier = baseMeasureUnit.getIdentifier();
done!

2021-09-16 18:54 UTC, younies commented on icu4c/source/i18n/measunit_extra.cpp
> +        identifier.set(reciprocal.getIdentifier());
done!

2021-09-16 18:54 UTC, younies commented on icu4c/source/i18n/measunit_extra.cpp
>  }
done!

2021-09-16 18:54 UTC, younies commented on icu4j/main/classes/core/src/com/ibm/icu/impl/units/UnitsData.java
> +        String identifier = MeasureUnit.fromMeasureUnitImpl(baseMeasureUnitImpl).getIdentifier();
done!

2021-09-21 05:32 UTC, sffc approved these changes
LGTM! Please squash

2021-09-21 16:43 UTC, sffc approved these changes

2021-09-21 19:06 UTC, merged