ICU-21814 Fixed a bunch of broken links
unicode-org/icu pull request #1919
Opened 2021-10-27 13:30 UTC by MrCheeze96

Most of the links on this page were broken. I've tried to see what the links was referring to and updated the links to what I found out to be most logical. If there is any link that doesn't go to the intended page, please feel free to change it to what it should be! :)

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21814
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [ ] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

2021-11-03 19:35 UTC, markusicu requested changes
Thanks!

Please prefix the commit message with `ICU-21814` plus one space.

2021-11-03 19:35 UTC, markusicu commented on docs/userguide/icu4c/packaging.md
> +The [ICU Source Code Organization](./index.md#icu-source-code-organization) section of
The fix of removing the slash is good, but please don't add the .md. The User Guide URLs are nicer/spiffier without the .md. --> https://unicode-org.github.io/icu/userguide/icu4c/index#icu-source-code-organization

2021-11-03 19:35 UTC, markusicu commented on docs/userguide/icu4c/packaging.md
> +ICU consists of a number of different libraries. The library dependency chart in the [Design](../icu/design.md#library-dependencies-c)
Ditto: The fix of adding `icu/` is good but please don't add `.md`.

2021-11-03 19:35 UTC, markusicu commented on docs/userguide/icu4c/packaging.md
> +See [ICU Binary Compatibility](../icu/design.md#icu-binary-compatibility) for
```suggestion
See [ICU Binary Compatibility](../icu/design#icu-binary-compatibility) for
```

2022-04-04 19:21 UTC, markusicu commented
After tomorrow, this will need to target ICU 72 via ticket [ICU-21959](https://unicode-org.atlassian.net/browse/ICU-21959).

2022-09-09 23:38 UTC, markusicu commented
> After tomorrow, this will need to target ICU 72 via ticket [ICU-21959](https://unicode-org.atlassian.net/browse/ICU-21959).

ICU 72 is nearing code freeze...

2026-06-30 23:55 UTC, koppor commented
The file https://github.com/unicode-org/icu/blob/main/docs/userguide/icu4c/packaging.md looks a bit different. Not sure whether the conflicts should be resolved or the PR closed - and redone if necessary?

2026-07-01 16:48 UTC, mihnita commented
I've recently fixed many broken links, ticket ICU-23425.
* aebe72cbafc 2026-06-26 19:38:37 +0000 Mihai Nita           ICU-23425 More broken links and redirects
* 7edf6ee6a8e 2026-06-23 18:11:00 -0700 Mihai Nita           ICU-23425 More broken links, Jekyll bug
* d5fd603fd45 2026-06-22 22:31:32 +0000 Mihai Nita           ICU-23425 Fix broken links in documentation site

That is what produced this reported conflict.

I checked all the links that this CL tried to fix, and they are already fixed by my commits. Sorry, I didn't know about this PR...

Anyway, I think at this point everything we could fix on ICU side is fixed (at least the problems detected by the [W3C Link Checker](https://validator.w3.org/checklink), plus 2 more tools). \
There are a few things that I need to report to CLDR.

I propose we close this PR.

2026-07-01 16:49 UTC, closed without merging