ICU-21900 Add ICU4C samples check to workflow for BRS "Test C Samples"
unicode-org/icu pull request #2010
Opened 2022-02-26 00:54 UTC by sven-oly

##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-_____
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [X] Tests included, if applicable
- [X] API docs and/or User Guide docs changed or added, if applicable

2022-02-26 01:25 UTC, sven-oly commented
This should automate the tests of ICU4C samples under source for BRS line 40. This is an automation of the [steps here:](https://unicode-org.github.io/icu/processes/release/tasks/healthy-code.html#linux-unix-build-and-test).

I look forward to your feedback.

2022-02-28 22:31 UTC, gnrunge requested changes

2022-02-28 22:31 UTC, gnrunge commented on .github/workflows/icu_ci.yml
> +          cd samples
This step lacks 'run: |'.

2022-02-28 22:31 UTC, gnrunge commented on .github/workflows/icu_ci.yml
> +          export PATH=$PATH:$PREFIX/bin
This and the following statement are intended for the next step ('Build and run samples'). As such they should be in the next step, perhaps in an 'env:' clause.

2022-03-01 23:13 UTC, sven-oly commented
Please take another look.

2022-03-02 16:05 UTC, gnrunge submitted a review, later dismissed

2022-03-02 16:42 UTC, gnrunge approved these changes

2022-03-02 17:25 UTC, merged

2022-03-02 18:43 UTC, jefgen commented
Thanks for doing this! :)