ICU-21957 fix NumberFormatterSettings::unitDisplayCase status, remove FormattedNumber:getGender
unicode-org/icu pull request #2185
Opened 2022-09-15 18:32 UTC by pedberg-icu

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21957
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

Fix some status problems in numberformatter.h found during the BRS task to check non-stable API macros. Per TC discussion 2022-09-15:
- For NumberFormatterSettings::unitDisplayCase, restore the status to `@internal` with a note indicating future removal.
- For FormattedNumber:getGender, remove it now (along with implementation and test)

2022-09-15 20:21 UTC, markusicu approved these changes
lgtm tnx

2022-09-15 20:30 UTC, markusicu requested changes
actually, we said we would remove the tech preview apis in 73. they were never stable, so we are not replacing something stable with something draft.

2022-09-15 20:30 UTC, markusicu commented on icu4c/source/i18n/unicode/numberformatter.h
> +     * in ICU 74, in favor of `displayOptions`
```suggestion
     * in ICU 73, in favor of `displayOptions`
```

2022-09-15 20:30 UTC, markusicu commented on icu4c/source/i18n/unicode/numberformatter.h
> +     * in ICU 74, in favor of `displayOptions`
```suggestion
     * in ICU 73, in favor of `displayOptions`
```

2022-09-15 21:07 UTC, pedberg-icu commented on icu4c/source/i18n/unicode/numberformatter.h
> +     * in ICU 74, in favor of `displayOptions`
Thanks, changed

2022-09-15 21:07 UTC, pedberg-icu commented on icu4c/source/i18n/unicode/numberformatter.h
> +     * in ICU 74, in favor of `displayOptions`
Thanks, changed

2022-09-15 21:07 UTC, markusicu approved these changes
lgtm tnx again

2022-09-15 23:51 UTC, pedberg-icu commented
Bizarre. The one test failure is for ICU4J, but this PR did not make any changes for ICU4J.

2022-09-16 03:55 UTC, sffc approved these changes

2022-09-16 15:34 UTC, merged

2022-09-16 15:34 UTC, pedberg-icu commented
Re-running the tests fixed the failure.