ICU-22295 Remove deprecated RBBI LBCMNoChain option
unicode-org/icu pull request #2397
Opened 2023-03-23 19:56 UTC by gz83

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22295
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [ ] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

2023-03-23 21:38 UTC, markusicu commented
> Since I haven't received any further response on unicode-org.atlassian.net for days and haven't seen an issue assigned, I take the liberty of making this PR without permission.

Thanks!
I am not familiar with the code, but at a glance, this looks plausible.
I wonder if @aheninger might have a couple of minutes to look this over?

2023-03-24 00:05 UTC, aheninger requested changes

2023-03-24 06:04 UTC, aheninger approved these changes

2023-03-24 16:33 UTC, markusicu commented
Great, thanks to both of you! I have asked the team to mark the ticket as "accepted" and merge the PR.

2023-03-24 19:59 UTC, merged