ICU-22220 Add step for updating API Doc table
unicode-org/icu pull request #2400
Opened 2023-03-24 21:50 UTC by sven-oly

This adds steps to revise the table of API docs in README.md with updated version numbers for either the Dev or Released entries.

##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22220
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

2023-03-24 22:01 UTC, markusicu requested changes
You are targeting the main branch with the 73rc BRS ticket. main goes into 74 now.
Please either retarget your PR to the maint/maint-73 branch, or use a ticket like ICU-22323 or ICU-22325.

2023-03-25 00:02 UTC, sven-oly commented
I think I've addressed the comments. Ready to go?

2023-03-27 21:07 UTC, markusicu commented on docs/processes/release/tasks/docs.md
> +#### Update table os API docs:
```suggestion
#### Update table of API docs:
```

2023-03-29 17:53 UTC, sven-oly commented
I think I've adopted the suggestions. PTAL.

2023-03-29 18:23 UTC, markusicu approved these changes
lgtm tnx

2023-03-29 18:25 UTC, merged