ICU-22342 Implement ExternalBreakEngineAPI
unicode-org/icu pull request #2418
Opened 2023-04-11 17:23 UTC by FrankYFTang

##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22342
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [ ] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

2023-06-21 18:40 UTC, FrankYFTang commented
PING @aheninger @pedberg-icu

2023-06-27 15:59 UTC, FrankYFTang commented
PING @aheninger @pedberg-icu @markusicu

2023-07-20 00:45 UTC, FrankYFTang commented
ping

2023-07-31 16:28 UTC, FrankYFTang commented
@richgillam It seems Peter is busy. I wonder would you have time to review this ?

2023-07-31 18:16 UTC, richgillam approved these changes
I don't know that I have the background to review this properly, but it all looks pretty straightforward and sensible to me...

2023-07-31 18:16 UTC, richgillam commented on icu4c/source/common/brkeng.cpp
> +    UText *text, int32_t, int32_t endPos, UVector32 &foundBreaks,
What's the unnamed `int32_t` parameter here?  From context, it looks like it'd be `startPos`.  If the caller passes you a `startPos`, why are you not using it?  Or is it something else?

2023-07-31 18:16 UTC, richgillam commented on icu4c/source/common/brkeng.cpp
> +const LanguageBreakEngine *
Probably want a blank line here...

2023-07-31 20:25 UTC, pedberg-icu approved these changes
Sorry for the late review. Looks reasonable.

2023-08-01 00:42 UTC, aheninger requested changes

2023-08-01 02:32 UTC, FrankYFTang commented on icu4c/source/common/unicode/rbbi.h
> +     * object methods of RuleBasedBreakIterator to avoid undefined behavior.
so are you suggesting we do not provide a unregisterExternalBreakEngine method but free the object internally in u_cleanup()?

2023-08-01 02:32 UTC, FrankYFTang commented on icu4c/source/common/brkeng.cpp
>          fEngines = engines.orphan();
done

2023-08-01 02:32 UTC, FrankYFTang commented on icu4c/source/common/unicode/rbbi.h
> +    virtual UBool isFor(UChar c, const char* locale) const = 0;
done

2023-08-03 04:53 UTC, aheninger requested changes
More to come, but a bit later.

2023-08-03 04:53 UTC, aheninger commented on icu4c/source/common/brkeng.cpp
> +    ExternalBreakEngine* engine, UErrorCode& status) {
This adopts `engine`, so it should probably delete it in case of failure. Use LocalPointers.

2023-08-03 04:53 UTC, aheninger commented on icu4c/source/common/brkeng.cpp
> +    ExternalLanguageBreakEngine* wrapper = new ExternalLanguageBreakEngine(engine);
Missing error checking for failed `new`

2023-08-03 04:53 UTC, aheninger commented on icu4c/source/common/brkeng.cpp
> +ExternalLanguageBreakEngine::ExternalLanguageBreakEngine(
Adopting constructors are troublesome for error handling. Ideally you would want to delete  `engine` on failure, but if the memory allocation for the new object fails, the constructor code won't be run, so you can't do it here.

LocalPointers can make it work, although it's a bit obscure. Look up passing std::unique_ptr as function parameters - they're very similar to LocalPointers.
Or, just deal with it at the call site.

2023-08-03 04:53 UTC, aheninger commented on icu4c/source/common/brkeng.cpp
>          LocalPointer<UStack>  engines(new UStack(_deleteEngine, nullptr, status), status);
You could completely remove the `_deleteEngine()` function by making `LanguageBreakEngine` derive from `UObject` and using `uprv_deleteUObject()`

2023-08-04 03:59 UTC, aheninger commented on icu4c/source/common/brkeng.cpp
> +    result = delegate->fillBreak(text, rangeStart, rangeEnd, foundBreaks.getBuffer(),
`foundBreaks.getBuffer()`, should be `foundBreaks.getBuffer()+beforeSize` ?
Looks like the code is setting up  to append, then writes at the start of `foundBreaks`.

2023-08-08 22:43 UTC, FrankYFTang commented on icu4c/source/common/brkeng.cpp
> +    ExternalLanguageBreakEngine* wrapper = new ExternalLanguageBreakEngine(engine);
Done by using LocalPointer now.

2023-08-09 01:00 UTC, FrankYFTang commented on icu4c/source/test/intltest/rbbitst.cpp
> +      // We implmement this for any locale, not return false for some langauge
fixe

2023-08-09 04:01 UTC, srl295 commented on icu4c/source/common/unicode/rbbi.h
> +     * object methods of RuleBasedBreakIterator to avoid undefined behavior.
agreed that u_cleanup() is the most important. Very unlikely for an app to make calls itself during shutdown. 

Unregister makes sense IF ICU can verify that it's not pulling the rug out from under users who already have created break instances.

2023-08-09 04:04 UTC, srl295 commented on icu4c/source/common/unicode/rbbi.h
> +     * object methods of RuleBasedBreakIterator to avoid undefined behavior.
Agreed. ICU should be able to invalidate its cache if need be here, on registry.

2023-08-09 04:04 UTC, srl295 commented
definitely support this idea and want to give this a more thorough review

2023-08-17 01:09 UTC, FrankYFTang commented
See https://docs.google.com/document/d/1o6FDnf1fVZTETOPlQvwR_XrE_O1F--qIjGyhkCCVnI8/edit#heading=h.v4537jydx0ge

2023-08-17 19:12 UTC, FrankYFTang commented on icu4c/source/common/unicode/rbbi.h
> +     * object methods of RuleBasedBreakIterator to avoid undefined behavior.
After ICUTC approve my amendment this morning I change this PR to remove the unregister function. PTAL

2023-08-17 19:13 UTC, FrankYFTang commented on icu4c/source/common/unicode/rbbi.h
> + * @draft ICU 74
After ICUTC approve my amendment this morning I change this PR to mark them as "Technology Preview". PTAL

2023-08-17 20:40 UTC, richgillam reviewed
Generally looks okay, but I have a few questions.

Also, I thought Andy had a block on this PR, but it looks like he removed it.  I'm still kind of hoping he can review this again before you check in.

2023-08-17 20:40 UTC, richgillam commented on icu4c/source/common/brkeng.cpp
> +            return lbe;
Aren't you still going to need a mutex around this code?  It seems like if `loadEngineFor()` can execute while you're trying to read the array, you could have it change out from under you.  For that matter, it doesn't looks like `loadEngineFor()` takes the mutex either, which compounds the problem.  Or am I missing something?

2023-08-17 20:40 UTC, richgillam commented on icu4c/source/common/brkeng.h
> + * a thin wrapper that delegate the task to ExternalLanguageBreakEngine
Should the second `ExternalLanguageBreakEngine` in this comment be `ExternalBreakEngine`?  That's what the code below seems to be saying.

Also, the naming here is kind of confusing: You have `LanguageBreakEngine`, `ExternalBreakEngine`, and `ExternalLanguageBreakEngine`, and it's not clear what their relationship is to one another.

2023-08-17 20:40 UTC, richgillam commented on icu4c/source/common/brkeng.cpp
> +    fEngines->push(wrapper.getAlias(), status);
Don't you need a mutex around `fEngines` here (or around this whole function)?

2023-08-18 17:15 UTC, FrankYFTang commented on icu4c/source/common/rbbi.cpp
> +    umtx_initOnce(gLanguageBreakFactoriesInitOnce, &initLanguageFactories, status);
I change it to a common function.

2023-08-18 20:26 UTC, richgillam submitted a review, later dismissed
Sold!  Thank you for the changes!

2023-08-28 23:45 UTC, FrankYFTang commented
@aheninger @richgillam PTAL

2023-08-29 15:11 UTC, richgillam approved these changes
Rubber stamp, assuming nothing significant has changed since the last time I approved (can't really tell because the commits have been squashed).

2023-08-30 18:43 UTC, merged