ICU-22583 BRS74: Version number update for 74.2
unicode-org/icu pull request #2728
Opened 2023-12-07 14:19 UTC by rp9-next

##### Checklist

- [ ] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-_____
- [ ] Required: The PR title must be prefixed with a JIRA Issue number. 
- [ ] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [ ] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [ ] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

2023-12-07 15:20 UTC, markusicu submitted a review, later dismissed
lgtm tnx!

2023-12-07 16:45 UTC, mihnita commented
The java versions (all the `pom.xml`) files should use a `-SNAPSHOT` version. So `7.2-SNAPSHOT`

2023-12-08 20:58 UTC, markusicu commented
> @rp9-next Please resolve the merge conflict; I can then re-approve.

The conflict is in .../icuver.txt, so the Java .../icudt74b/icuver.res will need to be updated too.
FYI @mihnita

2023-12-08 21:34 UTC, mihnita commented on icu4j/releases_tools/shared.sh
> +export github_rel_version='74_2'
No big deal.
That's a script I prepared to build and zip all the release files, including zipped complete javadoc and all.
But the release was done by Yoshito "by hand"

2023-12-08 21:35 UTC, mihnita approved these changes
Thank you, lgtm

2023-12-08 23:12 UTC, echeran approved these changes
rslgtm

2023-12-09 00:12 UTC, markusicu requested changes
Thanks for updating icuver.txt, but as I said before, that's incomplete without also updating the corresponding icuver.res in the Java tree.

2023-12-09 02:32 UTC, mihnita commented
Submitted as PR https://github.com/unicode-org/icu/pull/2734

2023-12-09 02:32 UTC, closed without merging