ICU-22580 Address infinity loop in RBBI
unicode-org/icu pull request #2735
Opened 2023-12-08 23:47 UTC by FrankYFTang

##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22580
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [X] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

2023-12-09 02:09 UTC, aheninger requested changes

2023-12-09 09:56 UTC, FrankYFTang commented on icu4c/source/test/intltest/rbbiapts.cpp
> +                 UnicodeString rule = {u1, u2, 0};
DONE. PTAL

2023-12-09 09:56 UTC, FrankYFTang commented
PTAL

2023-12-11 06:49 UTC, aheninger approved these changes

2023-12-11 19:34 UTC, merged