ICU-22602 Fix stack overflow inside flattenVariables
unicode-org/icu pull request #2740
Opened 2023-12-13 00:27 UTC by FrankYFTang

Limit the recursive call of flattenVariables to maximum depth 4000 since Java on my machine throw stack overflow exception around 4300.

##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22602
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [ X Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [ ] Issue accepted (done by Technical Committee after discussion)
- [X] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

2023-12-13 00:52 UTC, richgillam submitted a review, later dismissed

2023-12-13 01:55 UTC, richgillam commented
It'd really make reviewing easier if you'd wait to squash until the fix is ready to go in.  What's changed since the last time I looked at this?

2023-12-13 02:01 UTC, FrankYFTang commented
> It'd really make reviewing easier if you'd wait to squash until the fix is ready to go in. What's changed since the last time I looked at this?

sorry, Java 11 stackoverflow when the depth reach 3906 so I have to change the limit from 4000 to 3500 and somehow I forgot to remove a println in the Java code.

2023-12-13 02:04 UTC, richgillam commented
> sorry, Java 11 stackoverflow when the depth reach 3906 so I have to change the limit from 4000 to 3500 and somehow I forgot to remove a println in the Java code.

Ah.  Okay, that all sounds reasonable.

2023-12-13 02:05 UTC, richgillam approved these changes

2023-12-13 03:21 UTC, aheninger requested changes

2023-12-13 03:21 UTC, aheninger commented on icu4c/source/common/rbbinode.cpp
> +    if (depth > kRecursiveDepthLimit) {
Need to check for an incoming error first, and not overwrite an existing error with a new one.

2023-12-13 03:21 UTC, aheninger commented on icu4j/main/core/src/test/java/com/ibm/icu/dev/test/rbbi/RBBITest.java
> +            // expected exception with unpaired surrogate.
Comment is from another test. Copy-paste error.

2023-12-13 20:53 UTC, richgillam approved these changes
It looks to me like you addressed Andy's comments, but you might still need him to confirm that himself...

2023-12-14 22:05 UTC, aheninger approved these changes

2023-12-14 23:14 UTC, merged