ICU-22633 Fix Integer-overflow in icu_75::Calendar::add
unicode-org/icu pull request #2805
Opened 2024-01-23 00:52 UTC by FrankYFTang

##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22633
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [X] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

2024-01-23 04:50 UTC, roubert requested changes
This unit test won't fail even without the bugfix. I think it'd be better if the unit test fails unless overflow is handled correctly, to prevent any accidental regressions by future changes here.

2024-01-23 17:17 UTC, FrankYFTang commented
It fail under undefined sanitiser build

On Mon, Jan 22, 2024, 8:50 PM Fredrik Roubert ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> This unit test won't fail even without the bugfix. I think it'd be better
> if the unit test fails unless overflow is handled correctly, to prevent any
> accidental regressions by future changes here.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/unicode-org/icu/pull/2805#pullrequestreview-1837854013>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJ2N2KIHI64INQDESQPI6ATYP46QRAVCNFSM6AAAAABCGDRCNKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMZXHA2TIMBRGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-24 00:02 UTC, roubert commented
> Without the fix, the added unit test show the following under UndefinedBehaviorSanitizer

Sure, but few people (maybe even none) regularly build using the UndefinedBehaviorSanitizer during their normal work on ICU, so then any change that happens to break this by mistake will become an unpleasant surprise next time the UndefinedBehaviorSanitizer is run. I think it'd be better with a unit test that simply failed in any build mode unless overflow was handled correctly.

2024-01-24 23:34 UTC, FrankYFTang commented
> > Without the fix, the added unit test show the following under UndefinedBehaviorSanitizer
> 
> Sure, but few people (maybe even none) regularly build using the UndefinedBehaviorSanitizer during their normal work on ICU, so then any change that happens to break this by mistake will become an unpleasant surprise next time the UndefinedBehaviorSanitizer is run. I think it'd be better with a unit test that simply failed in any build mode unless overflow was handled correctly.

ok, I change the test. PTAL

2024-01-27 02:01 UTC, richgillam reviewed
Same questions as the other integer-overflow PR.

2024-01-29 16:12 UTC, roubert commented
> ok, I change the test. PTAL

That's better, thanks, but there's still no test case that fails without the bugfix for `ClockMath::floorDivide()`, meaning that it would be all too easy to reintroduce that bug by mistake without causing any test failure. I think it'd be much better if there were test cases covering all the bugs that you fix, to prevent such bugs from being reintroduced again. The fact that this code has had these bugs for so long without anyone noticing until now shows just how easy it is to do such mistakes.

2024-01-30 23:36 UTC, FrankYFTang commented on icu4c/source/i18n/calendar.cpp
> +        int64_t era = get(UCAL_ERA, status);
no, I am not changing the get to int64_t , it returned int32_t but the era is int64_t so later on when it += amount, it will not overflow int32_t

2024-01-30 23:58 UTC, FrankYFTang commented on icu4c/source/i18n/calendar.cpp
> +        }
done

2024-01-31 00:00 UTC, FrankYFTang commented
> > ok, I change the test. PTAL
> 
> That's better, thanks, but there's still no test case that fails without the bugfix for `ClockMath::floorDivide()`, meaning that it would be all too easy to reintroduce that bug by mistake without causing any test failure. I think it'd be much better if there were test cases covering all the bugs that you fix, to prevent such bugs from being reintroduced again. The fact that this code has had these bugs for so long without anyone noticing until now shows just how easy it is to do such mistakes.

I agree. but I have hard time to figure out how to craft one.

2024-01-31 11:34 UTC, roubert commented
> I agree. but I have hard time to figure out how to craft one.

OK, I see, `ClockMath::floorDivide()` never returns any wrong results, also not in the existing version without the bugfix, it just has an internal overflow where the numbers wrap around from negative to positive, which doesn't affect the result of the subtraction (but triggers the sanitizer).

That's nothing that can (or needs to be) unit tested.

2024-01-31 11:38 UTC, roubert approved these changes
LGTM

2024-02-01 21:49 UTC, merged