ICU-21810 Fix memory allocation error check
unicode-org/icu pull request #3039
Opened 2024-06-13 22:49 UTC by FrankYFTang

##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21810
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

2024-06-14 17:29 UTC, roubert requested changes

2024-06-14 17:29 UTC, roubert commented on icu4c/source/common/ucurr.cpp
> +    *currencySymbols = nullptr;
I'd suggest that you move this statement to inside of the if-statement, together with setting `*total_currency_name_count` and `*total_currency_symbol_count`, that would be more logical grouping.

2024-06-14 17:29 UTC, roubert commented on icu4c/source/common/ucurr.cpp
> +        uprv_free(*currencyNames);
You should also set this to `nullptr`.

2024-06-17 19:20 UTC, FrankYFTang commented
PTAL

2024-06-17 19:47 UTC, roubert approved these changes
LGTM

2024-06-17 22:33 UTC, merged