ICU-22923 ICU BRS 77: front-load update version to 77.0.1
unicode-org/icu pull request #3297
Opened 2024-12-10 18:51 UTC by mihnita

#### Checklist
- [x] Required: Issue filed: ICU-22923
- [x] Required: The PR title must be prefixed with a JIRA Issue number. Example: "ICU-1234 Fix xyz"
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. Example: "ICU-1234 Fix xyz"
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

2024-12-10 19:08 UTC, markusicu requested changes
changes lgtm but the ticket is wrong -- it's the release ticket.
please use the rc ticket: ICU-22922

2024-12-10 19:08 UTC, markusicu commented on docs/processes/release/tasks/versions.md
> +### CLDR-to-ICU onversion
```suggestion
### CLDR-to-ICU Conversion
```

2024-12-10 19:08 UTC, markusicu commented on icu4c/source/configure
no configure.in changes?

2024-12-10 20:13 UTC, mihnita commented on icu4c/source/configure
Not listed here:
https://unicode-org.github.io/icu/processes/release/tasks/versions.html

And I don't see any `configure.in` file.

```sh
$ find . | grep -i configure
./icu4c/source/configure.ac
./icu4c/source/configure
./icu4c/source/runConfigureICU
./icu4c/as_is/os400/convertConfigure.sed
```

Other than that:
* I tested everything (icu4c and icu4j)
* I compared the CL that did the front-load for 76.0.1 and this one
  They are the same, with the only differences in `tools/cldr/cldr-to-icu` (the change from yesterday) and one change missing from the component that was shared with cldr and was removed last quarter. So all accounted for.

2024-12-10 20:19 UTC, mihnita commented
> changes lgtm but the ticket is wrong -- it's the release ticket. please use the rc ticket: [ICU-22922](https://unicode-org.atlassian.net/browse/ICU-22922)

DONE, thanks.

2024-12-11 00:40 UTC, markusicu reviewed
lgtm tnx

pse squash, and remember to fix the ticket number in the commit message

2024-12-11 00:45 UTC, mihnita commented
> lgtm tnx
> 
> pse squash, and remember to fix the ticket number in the commit message

Thank you.
Sqashed, used "ICU-22922" in description

2024-12-11 00:50 UTC, markusicu approved these changes

2024-12-11 03:15 UTC, merged