ICU-22954 USet C++ iter samples no UnicodeString
unicode-org/icu pull request #3316
Opened 2024-12-23 19:53 UTC by markusicu

... to make the sample code work without U_SHOW_CPLUSPLUS_API as discussed in https://github.com/unicode-org/icu/pull/3295#discussion_r1892174805

I am also moving the non-sample code above the commented-out sample code, for clarity.

#### Checklist
- [x] Required: Issue filed: ICU-22954
- [x] Required: The PR title must be prefixed with a JIRA Issue number. Example: "ICU-1234 Fix xyz"
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. Example: "ICU-1234 Fix xyz"
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

2024-12-27 06:41 UTC, roubert requested changes

2024-12-27 06:41 UTC, roubert commented on icu4c/source/common/unicode/uset.h
> + *     u_strToUTF8WithSub(utf8, 199, nullptr, s.data(), len32, 0xFFFD, nullptr, errorCode);
Considering how many of these Frank has fixed just in the past few years, to correct off-by-one errors and hardcoded lengths forgotten when buffere sizes were changed, I think it's a really good idea to use `UPRV_LENGTHOF` or `sizeof` expressions even in commented-out sample code.

2025-02-05 21:41 UTC, markusicu commented on icu4c/source/common/unicode/uset.h
> + *     u_strToUTF8WithSub(utf8, 199, nullptr, s.data(), len32, 0xFFFD, nullptr, errorCode);
done

2025-02-05 21:42 UTC, markusicu commented
feedback addressed; @roubert @richgillam @eggrobin PTAL

2025-02-05 21:47 UTC, richgillam approved these changes
LOKTM

2025-02-05 22:47 UTC, merged