ICU-11533 Myanmar calendar support - suggestion to add [WIP]
unicode-org/icu pull request #630
Opened 2019-04-22 00:06 UTC by mapmeld

This is still a work in progress, but as an ICU and C++ newbie, I am reaching out for advice - for example tests ignored my calendars with calendar=myanmar, so this code overwrites calendar=buddhist ... this is not my intent. Any help on setup, please contact me here or @mapmeld on Twitter.

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-_____
- [x] Updated PR title and link in previous line to include Issue number
- [ ] Issue accepted
- [x] Tests included
- [ ] Documentation is changed or added

CLDR ticket: https://unicode.org/cldr/trac/ticket/8081
Unicode / ICU ticket: https://unicode-org.atlassian.net/browse/ICU-11533

The code implements the Burmese/Myanmar lunisolar calendar for festival / holiday dates.  Some people in Myanmar use this calendar on official documents and forms, e.g. their birthdate, and it is not simple to convert between them.

### Comparing to a working reference

I am using the open source C++ and JS implementations from https://github.com/yan9a/mcal and making changes:
- renaming variables so their meaning is easier to understand
- changing variable type from long to int where a long is not needed (e.g. day / month / year )
- numbering months in chronological order
- using ClockMath.floorDivide instead of importing math.h ... but is this necessary? Following other calendar implementations
Currently the tests appear to have off-by-one errors (1 month and 1 day off) in most cases.

### Help with development

As mentioned earlier, development would be better if I can create calendar=myanmar separate from calendar=buddhist. Also I currently run *all* icu4c tests with ```make check``` instead of the ones which I am targeting - Any help on setup, please contact me here or @mapmeld on Twitter.

### CLA

I have signed the CLA. Because the C++ code is based on Yan Naing Aye's repo, I've filed an Issue asking if he would sign the CLA as well.

2019-04-22 02:49 UTC, mapmeld commented
I changed the PR so it is more legible - I no longer overwrite BuddhistCalendar

Here are the errors which I see preventing creation of a new calendar type (these errors do not raise when I overwrote an existing calendar)

```
 UObjectTest {
         testIDs {
         FAIL: dynamicID != staticID! MyanmarCalendar * x= Calendar::createInstance(Locale("@calendar=myanmar"), status);  - (Are you missing data?)

         } ERRORS (1) in testIDs (16ms)

...

TestMyanmarFormat {
         Expected Tagu 10, 1350 ME but got April 14, 1989 AD
         Parse incorrect of Tagu 10, 1350 ME - wanted 608603000000 but got 0, December 31, 1969 AD
         U_ILLEGAL_ARGUMENT_ERROR : Error occurred testing Myanmar Calendar in English  - (Are you missing data?)

         } ERRORS (3) in TestMyanmarFormat
```

2019-04-24 22:03 UTC, srl295 commented on .gitignore
> +icu4c/source/test/*/*test-*.txt
These are good but unrelated changes. please move the .gitignore changes to a new PR against one of:

- https://unicode-org.atlassian.net/browse/ICU-20068
- https://unicode-org.atlassian.net/browse/ICU-20527

2019-04-24 22:04 UTC, srl295 commented on icu4c/source/data/lang/en.txt
> +            myanmar{"Myanmar Calendar"}
so, this data is from CLDR. So what's here is for the sake of a prototype.

2019-04-24 22:06 UTC, srl295 commented on icu4c/source/data/locales/root.txt
> +        myanmar{
same comment, this file is derived, so changes need to be on the CLDR side.

2019-04-24 22:06 UTC, srl295 commented on icu4c/source/data/misc/keyTypeData.txt
> +            myanmar{""}
I think this is derived from CLDR bcp47 data

2019-04-24 22:08 UTC, srl295 commented on icu4c/source/i18n/myancal.h
> + * Copyright (C) 2003-2013, International Business Machines Corporation
Probably don't need this 2003-2013 line and others (I assume this is copy and paste from buddhist as you said)

2019-04-24 22:08 UTC, srl295 commented on icu4c/source/i18n/myancal.h
> + * that implements the Persian calendar.  It is used as the official
oops… fix references to Persian

2019-04-24 22:09 UTC, srl295 commented on icu4c/source/i18n/myancal.h
> +  enum EMonths {
fix… persian

2019-04-24 22:09 UTC, srl295 commented on icu4c/source/i18n/myancal.h
> +  // TODO: copy c'tor, etc
drop this, it has a copy c'tor.

2019-04-24 22:10 UTC, srl295 commented on icu4c/source/i18n/ucal.cpp
> +ucal_inDaylightTime(    const    UCalendar*      cal,
(i think dropping the whitespace here is fine.)

2019-04-24 22:11 UTC, srl295 commented on icu4c/source/test/testdata/structLocale.txt
> +            myanmar{""}
Note, this file is not generated.

2019-04-24 22:12 UTC, srl295 commented on icu4c/source/i18n/myancal.cpp
> + * Copyright (C) 2003-2013, International Business Machines Corporation
fix date

2019-04-24 22:12 UTC, srl295 commented on icu4c/source/i18n/myancal.cpp
> +// © 2017 and later: Unicode, Inc. and others.
fix date, if there's a © from the original source please put it here

2019-04-24 22:12 UTC, srl295 commented on icu4c/source/i18n/myancal.cpp
> + *   12/28/2017  mapmeld     copied from persncal.cpp
aha, as suspected.

2019-04-24 22:13 UTC, srl295 commented on icu4c/source/i18n/myancal.cpp
> +    //  return 385;
?

2019-04-24 22:15 UTC, srl295 commented on icu4c/source/i18n/myancal.cpp
> +    c = ClockMath::floorDivide(1, (myan_year_type + 1)); //big wa and common yr
may be better `int32_t c = …` and don't declare above.

2019-04-24 22:15 UTC, srl295 commented on icu4c/source/i18n/myancal.cpp
> +    //myan_month--;
?

2019-04-24 22:15 UTC, srl295 commented on icu4c/source/i18n/myancal.cpp
> +    //myan_day++;
?

2019-04-24 22:17 UTC, srl295 commented on icu4c/source/i18n/myancal.cpp
> +// Myanmar does not change clocks for Daylight Time
hm. this may be true, but it is a property of the TZ not of the calendar.

2019-04-24 22:19 UTC, srl295 commented on icu4c/source/i18n/myancal.cpp
> +      printf("success\n");
printf… put it  behind `#if defined (U_DEBUG_CAL)  … #endif` and mention the file and line, see https://github.com/unicode-org/icu/blob/85c7e61b3e788be448a4ea96eb8861c1a4003d94/icu4c/source/i18n/gregocal.cpp#L377

2019-04-24 22:20 UTC, srl295 commented on icu4c/source/i18n/myancal.cpp
> +      printf("success\n");
(will also need `#if defined (U_DEBUG_CAL)  …   #include <stdio.h> … #endif` earlier in the source file)

2019-04-24 22:20 UTC, srl295 commented on icu4c/source/i18n/myancal.cpp
> +     printf("fail create Myanmar\n");
see above, debug printf

2019-04-24 22:20 UTC, srl295 commented on icu4c/source/i18n/myancal.cpp
> +    // out.
right. It's probably a low memory condition.

2019-04-24 22:22 UTC, srl295 commented
@mapmeld thanks for this!  The automated builds are failing (look for the red X's above), see https://travis-ci.org/unicode-org/icu/jobs/522911134#L1351 for example.

2019-05-08 19:21 UTC, mapmeld commented
@srl295 progress update / question: am I allowed to import math.h here? The other calendars use ```ClockMath::floorDivide``` instead, but it is giving me an unusual (negative) result on one line dividing doubles, causing everything to be shifted one lunar month later on in the code

```
ClockMath::floorDivide(double(SOLAR_YEAR * (long(myan_year) + 3739)), LUNAR_MONTH, excess_days);
```

2019-05-08 22:29 UTC, srl295 commented
@mapmeld `math.h` is probably OK, as `astro.cpp` and others use it.  If you can use the  `uprv_` functions such as `uprv_floor()` that gives a little more platform specific separation. 

Note that `floorDivide` is implemented via `uprv_floor(a/b)` which just calls `floor`.

2019-05-08 22:33 UTC, srl295 commented on icu4c/source/i18n/myancal.cpp
> +		i = ClockMath::floorDivide(l + u, 2);
change `long` to `int32_t` here and similar sites.

2019-05-08 22:33 UTC, srl295 commented on icu4c/source/i18n/myancal.h
> + * @author Mehran Mehr
fix

2020-03-24 22:14 UTC, srl295 commented
@mapmeld ping on this?

2020-03-25 19:53 UTC, mapmeld commented
I got formal approval from the original author of the C++ code. Unfortunately I haven't looked at this for a while, and never found a good way to debug what was happening. I feel like this is VERY close but only for someone who understands why it is usually off by one lunar month.

2020-03-25 20:01 UTC, srl295 commented
> I got formal approval from the original author of the C++ code. Unfortunately I haven't looked at this for a while, and never found a good way to debug what was happening. I feel like this is VERY close but only for someone who understands C++ and can find out why it is usually off by one lunar month.

didn't get to debug it but the 'month' field does start at 0 of course, that always gets me…  Can you rebase it against current master?

Also, if you didn't already do so, we'll definitely need a CLDR ticket for this, and the initial english/etc names should go there. IF you start a PR that adds the right stuff into CLDR's en.xml, etc, i can help with the data generation

2020-06-05 21:58 UTC, mapmeld commented
@srl295 sorry for another long delay on responding to the project. I've updated to the current master branch and reapplied my changes in one commit.  I have tests for MyanCal but they have been failing, off by one lunar month.  I don't know how to test my code without the entire ICU test suite, which makes it difficult for me to switch back and forth between coding and testing or printf-ing to figure out where I'm losing the correct values.

2022-11-07 19:41 UTC, markusicu commented
> @srl295 sorry for another long delay on responding to the project. I've updated to the current master branch and reapplied my changes in one commit. I have tests for MyanCal but they have been failing, off by one lunar month. I don't know how to test my code without the entire ICU test suite, which makes it difficult for me to switch back and forth between coding and testing or printf-ing to figure out where I'm losing the correct values.

This is what I do on Linux:
- git repo workspace in ~/icu/mine/src
- out of source build into ~/icu/mine/dbg/icu4c
- `cd ~/icu/mine/dbg/icu4c/test/intltest`
- `export LD_LIBRARY_PATH=../../lib:../../stubdata:../../tools/ctestfw`
- `make && ./intltest format/IntlCalendarTest`

2023-02-10 22:56 UTC, mapmeld commented
I rebased to make this current, in hopes that someone (possibly me, but happy to pass this on) can debug the tests

2024-06-13 00:25 UTC, mapmeld commented
After a long break, I've revisited this PR, rebased, added tests, and addressed most of the issues.
To keep dates verifiable I will probably limit the PR to more recent eras (1800 AD and onward)

Remaining issues:
- There's an off-by-one bug between summer 2016-2018 (different types of leap years). The current patch should be replaced by fixing the source of the off-by-one error
- a note says month names Late Tagu and Late Kason are for old eras, but they appear here and in the JS app (short explanation: if the date occurs at the end of the year it uses the name Late Tagu; for example incrementing the date from Late Tagu 11, 1350 ME -> Tagu 12, 1351 ME)
- I should add tests prior to 1989 AD, especially around the change of eras in 1895 and 1951. There is a test failing for 1609 AD which I don't remember where I found
- It's difficult to find reference for when a great leap year (additional day on Nayon) last occurred prior to 2015 AD

2024-06-17 00:22 UTC, macchiati requested changes
> I got formal approval from the original author of the C++ code. Unfortunately I haven't looked at this for a while, and never found a good way to debug what was happening. I feel like this is VERY close but only for someone who understands C++ and can find out why it is usually off by one lunar month.

If you are not the original author, then we will need the original author to sign a CLA also.

2024-06-17 16:08 UTC, mapmeld commented
@macchiati I didn't update the list and forgot this, but Yan9a signed the CLA in 2020: https://github.com/yan9a/mmcal/issues/2#issuecomment-574132201

2024-08-31 02:57 UTC, closed without merging

2024-09-01 00:59 UTC, srl295 commented
closed?

2025-04-19 01:33 UTC, mapmeld commented
I've made a comment on the issue tracker about implementing a Myanmar year + era calendar (similar to the Thai / buddhist / buddhcal currently in ICU) https://unicode-org.atlassian.net/browse/ICU-11533?focusedCommentId=182810 as that might be easier to implement and test