CLDR-13226 - Fix some minor issues
unicode-org/icu pull request #746
Opened 2019-08-10 09:56 UTC by sylvestre

##### Checklist

- [ ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13226
- [ ] Updated PR title and link in previous line to include Issue number
- [ ] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

2019-09-11 22:48 UTC, sven-oly commented
There are a couple of things that should be done with this PR:
a. The commit messages must include the issue information. Please see: http://site.icu-project.org/repository/gitdev#TOC-Review-commit-to-Unicode-master

b. Please take a look at the build failures and resolve them.

2019-11-06 18:08 UTC, sffc commented
@sylvestre please take a look at Craig's comment and the build failures.

2021-07-28 19:09 UTC, sven-oly approved these changes
Resolving this old PR

2022-10-27 16:19 UTC, markusicu commented
> There are a couple of things that should be done with this PR: a. The commit messages must include the issue information. Please see: http://site.icu-project.org/repository/gitdev#TOC-Review-commit-to-Unicode-master
> 
> b. Please take a look at the build failures and resolve them.

These issues are not resolved.

2022-10-28 22:08 UTC, markusicu requested changes
The typos have been fixed by other PRs now, and the code changes are not good. Nothing left to be done here. @echeran FYI

2022-10-28 22:08 UTC, markusicu commented on docs/userguide/icu_data/buildtool.md
> +similar on first glance but actually produce different output:
This was fixed a couple of years ago in PR #1506.

2022-10-28 22:08 UTC, markusicu commented on icu4c/source/common/edits.cpp
> -        changed = FALSE;
This looks bad. `changed` is a member variable, and when it's not set right, then the observable iterator state is wrong.

2022-10-28 22:08 UTC, markusicu commented on icu4c/source/common/rbbirb.cpp
> -    fRuleStatusVals     = NULL;
Bad change. If something goes wrong before this field is assigned a new UVector, then the object is left with this field unassigned.

2022-10-28 22:08 UTC, markusicu commented on icu4c/source/i18n/msgfmt.cpp
> +        case UMSGPAT_ARG_TYPE_SELECT:
This change seems like purely a matter of taste. The switch cases are probably in the order of their enum declaration, which is also a logical grouping. Better to leave as is.

Some of these changes, if we did want to make them, should be done in parallel in both C++ and Java, to keep the code in sync.

2022-10-28 22:09 UTC, closed without merging